// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfStartedFinal.Migrations
{
    [DbContext(typeof(ECommerceContext))]
    [Migration("20230517131336_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("CategoryFinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FSerialNo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductFinalIdProduct")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductFinalIdProduct");

                    b.ToTable("CategoriesFinal");
                });

            modelBuilder.Entity("ProductFinal", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductFUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("IdProduct");

                    b.ToTable("FProducts");
                });

            modelBuilder.Entity("CategoryFinal", b =>
                {
                    b.HasOne("ProductFinal", null)
                        .WithMany("CategoriesFinal")
                        .HasForeignKey("ProductFinalIdProduct");
                });

            modelBuilder.Entity("ProductFinal", b =>
                {
                    b.Navigation("CategoriesFinal");
                });
#pragma warning restore 612, 618
        }
    }
}
